### ISSUE TITLE
Selection Tree 구현 관련해서 질문이 있습니다.

### ISSUE THREAD

**Issue by evejaeyong** [DSLDataStorage/DS_Project_2_2023_2#1]
안녕하세요, 데이터구조설계 과목을 수강하는 2022202088 김재용입니다.

명세서에는 Run의 개수는 도서 분류 코드의 개수과 동일하다고 적혀 있는데, 이는 Run의 개수가 000부터 700까지 8개로 고정되어 있는 것인지, 아니면 Heap이 비어 있는 경우엔  Run의 수가 더 적어질 수 있는 것인지 궁금합니다.

감사합니다.

**Comment by DSLDataStorage** [comment]
Selection tree에서 Run의 개수는 8개로 고정되어 있으며, heap이 비어있더라도 run의 개수는 8개로 동일합니다.
