### ISSUE TITLE
EXIT 명령어 관련질문

### ISSUE THREAD

**Issue by jcg100** [DSLDataStorage/DS_Project_2_2023_2#10]
안녕하세요.
컴퓨터 공학부 2020202027 장현준입니다.

프로젝트 명세서에 EXIT가 나올 경우 프로그램을 종료한다고 되어있는데 만약 command.txt파일을 끝까지 다 읽어도 EXIT가 들어오지 않는다면 프로그램을 실행하고 있어야 하는지 궁금합니다.

**Comment by kimsangho611** [comment]
command.txt 파일을 끝까지 다 읽고 실행한 경우 EXIT가 없어도 종료하면 됩니다.
