### ISSUE TITLE
setBookData 함수 임의 변형에 대한 질문

### ISSUE THREAD

**Issue by zzz332choi** [DSLDataStorage/DS_Project_2_2023_2#11]
안녕하세요. 2022202064 최봉규입니다. LoanBookData.h에 있는 함수 setBookData에 대해 질문을 드리려 합니다.

초기 스켈레톤 코드에는 setBookData함수에는 laon_count를 제외한 파라미터에는 제목, 작가, 출판 년도, 분류 코드로 4개가 있습니다. 
LOAD시 loan_count를 받으면서 setBookData에서 한번에 정리하고 싶은데 파라미터를 5개로 사용하여 해당 함수를 조금 변형해서 사용해도 될지에 대해 여쭈어 봅니다. 

감사합니다.

**Comment by kimsangho611** [comment]
가능합니다.
