### ISSUE TITLE
SelectionTree의 Insert함수 질문

### ISSUE THREAD

**Issue by DwKwCs** [DSLDataStorage/DS_Project_2_2023_2#12]
안녕하세요. SelectionTree 구현 중 Insert함수에 대해 질문드립니다.

1. SelectionTree의 Insert함수에 인자를 추가해서 구현하고 싶은데 가능할까요?
2. 만약 1번이 가능하다면, 다른 함수를 구현할 때, 함수명을 변경하지 않고 함수의 반환 값이나 인자를 변경해서 구현해도 되는지 궁금합니다.

**Comment by kimsangho611** [comment]
최대한 주어진 함수를 활용하되 구현시 반드시 필요하다고 생각하는 경우 1과2번 모두 가능합니다

**Comment by DwKwCs** [comment]
답변 감사합니다.
