### ISSUE TITLE
PRINT_ST 오름차순 출력 관련 문의

### ISSUE THREAD

**Issue by SeoeunY** [DSLDataStorage/DS_Project_2_2023_2#13]
안녕하세요, 데구실 금분반 수강 중인 2022202061 양서은입니다.
Selection Tree를 구현하던 와중에 질문이 생겨 남깁니다.
PRINT_ST의 경우 책 이름을 기준으로 오름차순 출력을 해야한다고 명세서에 쓰여있는데
혹시 map 컨테이너를 사용해 구현해도 될까요??

감사합니다.

**Comment by kimsangho611** [comment]
가능합니다
