### ISSUE TITLE
Delete 함수와 Book Code에 따른 Book_Count에 대하여 질문드립니다.

### ISSUE THREAD

**Issue by PokaChips** [DSLDataStorage/DS_Project_2_2023_2#14]
안녕하세요, 데이터구조설계 과목 수강 중인 2020202030 한재연이라고 합니다.
다름이 아니라, 프로젝트 진행 중 Delete 함수에 대하여 궁금한 것이 있어 질문드립니다.

프로젝트 제안서에 의하면 Delete 함수는 "Selection Tree에서 root node에 저장된 도서를 제거하는 명령어" 라고 설명되어 있습니다.
해당 사항에 대하여, BpTree의 Data를 삭제하는 경우는 아예 생각하지 않아도 되는지 궁금합니다.

또한, 도서 분류 코드 별 대출 가능 권수가 나누어져 있는데, 이는 '각 도서마다 개별적으로' 적용되는 건지, 아니면 '그 코드를 가진 도서 모두 적용되는 건지' 궁금합니다.
예를 들어. A라는 책의 도서 코드가 000인 상태에서, BpTree의 Loan_Count가 3인 상태라면 해당 도서는 이후 ADD 시도 시 더 이상 BpTree에 접근하지 못하고 Selection Tree로 넘어가는 구조로 이해하고 있었습니다.
이러한 상황에서 A를 ADD 명령어로 추가 시 BpTree에 접근하지 못하고 Selection Tree로 넘어가는 것은 명백한 사실로 이해하고 있습니다.
이때 B라는 책의 도서 코드가 000일 때, 해당 책은 이미 000의 도서 코드는 A가 3만큼 차지하고 있으므로 B도 BpTree에 insert 되지 못하고 SelectionTree로 넘어가는 건지, 아니면  개별적으로 생각하여 정상적으로 BpTree에 insert되는지 궁금합니다.

많은 Data를 생각하는 경우라면 후자의 상황이 맞는 것 같긴 하지만.. 확실하게 하고 싶어 질문드렸습니다.
감사합니다.

**Comment by kimsangho611** [comment]
1. DELETE 함수에서 BpTree의 데이터를 삭제하는 경우는 없습니다. BpTree에서 도서가 삭제되는 경우는 BpTree에 저장된 도서가 대출 불가 도서가 되어 Selection tree로 전달 될 때만 삭제됩니다.
2. 당연히 도서마다 개별적으로 적용되는 사항입니다.
