### ISSUE TITLE
txt 파일 관련 질문입니다

### ISSUE THREAD

**Issue by lovejg** [DSLDataStorage/DS_Project_2_2023_2#16]
안녕하세요 2020202068 박찬영입니다.
그 프로젝트 제안서에 따르면 loan_book.txt에서 개행 문자로 Carriage Return and Line Feed(\r\n)을 사용한다고 표시돼 있습니다.
제가 최근에 코드를 짜면서 알게 된 바에 의하면 윈도우와 리눅스에는 개행이 다르고, 리눅스에서 getline을 쓰면 리눅스 개행을 인식,
윈도우에서 getline을 쓰면 윈도우 개행을 인식하는 것으로 알고 있습니다.
저희는 현재 리눅스 환경에서 코드를 짜고 실행을 하는데, 저는 \r\n이 윈도우에서의 개행이라고 알고 있습니다.
그러면 manager.cpp에서 command를 파싱하는 과정에서 따로 저희가 리눅스 환경에서 윈도우의 개행을 인식해서 파싱하도록
코드를 구성해줘야 하는 것인지 궁금합니다.
추가적으로 loan_book.txt 뿐 아니라 command.txt에서의 개행도 \r\n이 맞는지 궁금합니다.

**Comment by kimsangho611** [comment]
테스트할 텍스트 파일을 윈도우에서 생성을 하기때문에 \r\n로 한것이며 command에서도 동일합니다

따로 리눅스 환경에서 윈도우의 개행을 인식해서 파싱하도록 해도 되고 vscode를 사용하면 쉽게 변경해서 할수 있습니다

**Comment by sonshn** [comment]
안녕하세요!
비슷한 질문인 것 같아 이 이슈에 질문을 남기게 되었습니다. 우분투 터미널에서 cat log.txt 명령어를 실행했을 때 결과가 제대로 출력된다면 추후 채점을 진행했을 때 이상이 없는 것인지 궁금합니다. 또, 유니코드가 아닌 UTF-8 인코딩만을 고려하여 코드를 작성해도 되는지 궁금합니다.
감사합니다.

**Comment by kimsangho611** [comment]
네 log.txt에 결과가 제대로 출력되면 이상없고, utf-8 인코딩만 고려하여 작성해도 됩니다.

-----Original Message-----
