### ISSUE TITLE
명령어 인자 구분자 관련질문

### ISSUE THREAD

**Issue by ghost** [DSLDataStorage/DS_Project_2_2023_2#17]
ADD' 'book'\t'code'\t'author'\t'date
SEARCH_BP' 'book
SEARCH_BP' 'a' 'b
PRINT_ST' '100

' ': 공백
'\t': tab
위와같이 ADD 제외하고 전부 공백으로 구분하면 되는 건가요?
또한 구분자 때문에 오류가 날 경우를 대비해
가능하다면 예시 명령어 파일을 받고 싶습니다.

**Comment by kimsangho611** [comment]
제안서확인하시길 바랍니다

인자가 있는 명령어의 경우 모두 탭으로 구분합니다
