### ISSUE TITLE
도서분류 코드 000 입/출력 관련

### ISSUE THREAD

**Issue by ghost** [DSLDataStorage/DS_Project_2_2023_2#19]
2차 과제에서 도서분류 코드 000이 입력과 출력으로 올 경우,
다음 중 어느 것이 옳습니까?
1.
input:   book 000 test 2023 0
print:    book/000/test/2023/0
2.
input:   book 0 test 2023 0
print:    book/0/test/2023/0

**Comment by kimsangho611** [comment]
1번이 맞습니다.
