### ISSUE TITLE
ADD 커맨드에 관한 질문입니다.

### ISSUE THREAD

**Issue by zzz332choi** [DSLDataStorage/DS_Project_2_2023_2#2]
명세서에서 ADD 의 사용 예를 보면 다음과 같습니다.

ADD book 200 risa 1990

이때 커맨드 뒤의 내용인 "book 200 risa 1990" 이 내용에서 궁금증이 생겼습니다.

LOAD의 경우에 해당 정보들은 '\t"으로 구분하도록 되어있습니다.  하여 ADD의 정보 구분자 역시 "\t" 으로 이루어 졌는가에 대해 궁금하여 질문 드립니다. 

감사합니다.

**Comment by kimsangho611** [comment]
ADD 명령어도 "\t"으로 구분하여 진행하시길 바랍니다.
