### ISSUE TITLE
제출 파일관련

### ISSUE THREAD

**Issue by jcg100** [DSLDataStorage/DS_Project_2_2023_2#20]
과제 명세서를 확인하면 제출하는 파일은 소스코드(make와 텍스트 파일제외)와 보고서로 적혀있는데 make와 txt.파일은 제출안하는 것으로 이해하는 것이 맞는것입니까?

**Comment by kimsangho611** [comment]
네. .cpp와 .h와 pdf를 제외한 파일은 제출하지 않으면 됩니다.
