### ISSUE TITLE
selection tree 관련 질문

### ISSUE THREAD

**Issue by R-JANG-98** [DSLDataStorage/DS_Project_2_2023_2#21]
1) 이미 selection tree로 이동한 도서가 b+tree에 추가되는 경우는 없다고 가정하나요?
2) 1)의 경우가 있다면, loan_count를 만족하여 selection tree에 도서가 중복으로 추가되었을 때, loan_count는 2배로 처리해야 하나요?

**Comment by kimsangho611** [comment]
1. 해당 경우는 없습니다.
