### ISSUE TITLE
LoanBookHeap.h의 getRoot() 함수에 관한 질문

### ISSUE THREAD

**Issue by KimChaena** [DSLDataStorage/DS_Project_2_2023_2#3]
안녕하세요 컴퓨터정보공학부 2019202056 김채나입니다.
명세서의 조건 중 '반드시 제공되는 코드(github 주소 참고)를 이용하여 구현하며 작성된 소스 파일의 이름과 클래스와 함수 이름 및 형태를 임의로 변경하지 않는다.'고 되어 있습니다.
그러나 LoanBookHeap.h의 getRoot()함수의 반환형이 LoanBootHeap* 형으로 LoanBookHeapNode*형의 root와 맞지 않아 오류가 발생합니다. getRoot()함수를 수정하여 코드를 작성해도 될까요?

**Comment by kimsangho611** [comment]
네 해당 경우에는 수정하여 작성해도 됩니다.
