### ISSUE TITLE
b+tree 구현 관련 질문입니다.

### ISSUE THREAD

**Issue by ChoiEunchan** [DSLDataStorage/DS_Project_2_2023_2#4]
안녕하세요. 프로젝트 수행 중 의문이 들어서 글 남깁니다.
제안서 2페이지에 B+tree의 설명을 보면 대출 중인 도서를 B+tree에 저장한다고 나와있습니다.
이 부분을 loan_book.txt 에 작성되어 있는 책의 대출 권수가 1이상, 대출 코드 별 대출 가능 권수 미만인 경우에만 B+tree에 저장하는 것으로 이해했는데 제가 제대로 이해한 것이 맞는지 궁금합니다.
그게 아니라면 loan_book.txt파일에 저장된 책 정보를 모두 B+tree에 저장하는 것인지 궁금합니다.

감사합니다.
![b+_tree_question](https://github.com/DSLDataStorage/DS_Project_2_2023_2/assets/113488436/b1d7ce2e-48ea-47e2-9f52-cabfd98481bb)

**Comment by kimsangho611** [comment]
loan_book.txt 파일을 모두 B+-tree에 저장한다고 생각하시면 됩니다.

초기 파일에는 대출 가능 권수를 초과한 데이터는 없다고 가정하시면 됩니다.
