### ISSUE TITLE
B+ Tree 구현 관련 질문이 있습니다.

### ISSUE THREAD

**Issue by evejaeyong** [DSLDataStorage/DS_Project_2_2023_2#5]
안녕하세요 데이터구조설계 과목을 수강중인 2022202088 김재용입니다.

프로젝트 진행 중 궁금한 점이 생겨 질문 드리게 되었습니다.

1. 프로젝트 명세서에서 범위 검색을 하는 SEARCH_BP 명령어의 예시로 'SEARCH_BP a e'가 있고 이 결과는 asia, book, educated입니다.
그런데, a와 e 사이에 있는 책의 이름을 모두 출력하는 것이라면 educated는 포함되지 않을 것 같다고 생각해서 정확한 범위의 조건이 궁금해져서 질문 드립니다.

2. 범위 검색을 하는 SEARCH_BP 명령어에서 띄어쓰기가 없는 단어만 입력되는 것인지 궁금합니다.

3. 스켈레톤 코드에서 Manager.cpp 파일 안의 PrintSuccessCode 함수가 명세서와 다르게 되어 있어, 파라미터와 함수 내용을 변경하고 구현해도 되는지 궁금합니다.

4. 최대 대여 수를 넘겨서 B+ Tree에서 Selection Tree로 이동한 책을 ADD 명령어를 통해 입력받는 경우는 고려해줘야 하는지, 고려해야 한다면 어떻게 처리해야 하는지 궁금합니다. 

5. Selection Tree 구현 중에 deepCopy 함수가 있는데 이를 사용하지 않고 얕은 복사를 사용해서 구현해도 되는지 궁금합니다.

감사합니다.

**Comment by kimsangho611** [comment]
1. 해당 명령어의 경우 입력된 두 인자들로 사이의 도서를 모두 출력하는 것입니다. 예를 들어, 인자로 a와 c가 입력되면 a, b, c로 시작하는 도서를 모두 출력하는 것입니다.
2. 띄어쓰기가 있는 도서가 입력될 수 있으며, 명령어의 구분자는 \t으로 하면 됩니다.
3. 다르게 변경해도 됩니다.
4. 그런 경우는 없다고 가정하시면 됩니다.
5. 가능합니다.

**Comment by kimsangho611** [comment]
SEARCH_BP 명령어 관련하여 기준을 다시 명확하게 작성해두었으니 확인바랍니다.

**Comment by Nagnero** [comment]
조교님 데구설을 수강중인 22학번 연선우입니다
다름이 아니라 오늘 오전에 해당 이슈를 확인하고, 1번 항목에 대해 구현을 완료했습니다.
오전에 제가 확인했을 때는 초성에 대한 범위를 판단하는 것이 아니라, 
책 제목이 입력되었을 때 두 제목 사이의 데이터들을 출력하라고 확인했었습니다.

이미 그렇게 구현한 경우에도 고쳐야 할까요?

**Comment by kimsangho611** [comment]
안녕하세요. 연선우 학생,

해당 사항에 대해 우선 저의 불찰로 명확하게 기준을 제시하지 못하고 여러번 변경 된 것에는 죄송하다는 말을 먼저 전합니다.

아마 학생분이 구현하신 부분이랑 제안서대로 구현하는 것에는 문자열 비교 부분의 차이이기 때문에 큰 차이가 없을 것으로 판단됩니다.

따라서 해당 사항의 구현과 관련하여 제안서에 수정한 사항으로 변경하는 것이 좋을 것 같습니다. 

감사합니다.

-----Original Message-----

**Comment by Nagnero** [comment]
늦은 시간에 빠른 답변 주셔서 감사합니다!

한 가지 제안드리고 싶은 것은 많은 학생을 해당 깃허브 issue를 참고하여 프로젝트를 구현하는데,
중간에 어떤 history를 가지고 프로젝트가 변경되었는지 알 수 있으면 좋을 것 같습니다.

감사합니다.

**Comment by PangDae20** [comment]
안녕하십니까 데구설 수강중인 2020202019 방호영 입니다.
해당 답변 관련해서 궁금한 점이 있습니다.
수정된 제안서를 보게되면, PRINT_BP에서 인자를 두개를 받을 시 A<= ? <=C 로 대소관계가 포함되는 도서들을 모두 출력하라고
수정이 되어 있었습니다
그런데 출력 포멧 예시에서 인자가 a와 e 로 들어온 경우 educated까지 포함되어 출력이 되는데
이 경우 위에서 설명된 대소 관계에 맞지 않는 것으로 생각이 들어 질문 드립니다.
1. 혹시 인자가 단어가 아닌 알파벳 소문자로 하나의 문자인것인지
2. 범위에 대한 대소관계 표현이 잘못된 것인지 
궁금하여 질문 드립니다!

**Comment by kimsangho611** [comment]
A<= ? <=C 와 같이 대소로 표현한 이유는 a, b, c로 시작하는 도서명을 대소문자와 상관없이 모두 출력하라는 의미입니다.
따라서 a와 e가 인자로 들어온 경우 a, b, c, d, e로 시작하는 도서명을 대소문자와 상관없이 모두 출력하라는 의미입니다.

대소 관계에 너무 의존하지 마시고 두개의 인자가 들어오면 첫번째 인자로 들어온 알파벳으로 시작하는 도서명부터 
두번째 인자로 들어온 알파벳으로 시작하는 도서명을 모두 출력하면 됩니다.

-----Original Message-----

**Comment by PangDae20** [comment]
빠른 답변 감사합니다!
그럼 인자로 알파벳 소문자만 들어온다고 가정하고 진행하면 되는 것인지 궁금합니다.
올라온 제안서에서는 단어라고 설명이 되어 있어 고민이 되었습니다.

**Comment by kimsangho611** [comment]
소문자만 고려하시길 바랍니다.

-----Original Message-----

**Comment by PangDae20** [comment]
답변 감사 드립니다. 마지막으로 제가 이해 한것이 맞는지 여쭤보고 싶습니다.
1. 인자가 두 개일 경우 "알파벳 문자 하나씩" 두개가 들어온다
2. 인자로 시작되는 단어들을 포함한 도서들을 모두 출력한다.
3. 인자가 두 개 들어오게 되면 두 인자는 반드시 오름차 순으로 들어온다. ( ex) d a 와 같은 순은 고려하지않는다.)

**Comment by kimsangho611** [comment]
1. 맞습니다
2. 맞습니다.
3. 맞습니다.

-----Original Message-----
