### ISSUE TITLE
프로젝트 전반적인 질문드립니다.

### ISSUE THREAD

**Issue by jcg100** [DSLDataStorage/DS_Project_2_2023_2#6]
안녕하세요. 컴퓨터정보공학부 2020202027 장현준입니다.

1. 만약 ADD 명령어로 B+ 트리에 책을 추가한다면 이때 대출 권수를 0으로 하면 되는지 입니다.

2. print ST 명령어의 경우  Selection tree부터 시작해서 인자에 들어간 heap 에 담긴 모든 책을 출력하는 것이 맞는지 입니다.

3. log.txt가 이미 존재하는 경우 텍스트 파일 가장 뒤에 추가로 저장한다고 하였는데 프로그램을 두번 실행한다면 두 번의 결과가 모두 담긴다는 의미인 것인지 아니면 프로그램을 작동하여 오류가 발생하여도 오류 메시지만 출력하고 계속 진행하여 command에 적힌 명령어를 모두 실행해 그 결과를  log.txt에 저장하라는 것인지 입니다.

4. LoanBookHeep에서 heepifyup(down) 함수가 heap을 정렬할때 노드끼리의 변경에 사용되는 함수가 맞는 지 궁금합니다.

5. heap나 selection tree의 경우 링크드 리스트가 아닌 array형태로 동적할당 받아 진행하여도 되는지 궁금합니다.

6. 책의 년도나 작가의 이름의 경우 딱히 조건이 명시되어있지 않던데 상관하지 않아도 되는지 궁금합니다.

감사합니다.

**Comment by kimsangho611** [comment]
1. ADD 명령어로 추가할 때, 해당 도서가 없는 경우에는 0으로 하면 됩니다.
2. 맞습니다.
3. 프로그램을 두 번 실행하는 경우 두 번의 결과가 모두 담긴다는 의미가 맞습니다.
4. 네 맞습니다.
5. 본 프로젝트에서는 Linked list만 사용하시길 바랍니다.
6. 상관하지 않아도 됩니다.

**Comment by kang-tw** [comment]
안녕하세요 2020202002 강태웅입니다.
"5.본 프로젝트에서는 Linked list만 사용하시길 바랍니다."

관련하여서 분류코드에 따른 총 8개의 heap을 관리하기 위해  하나의 LoanBookHeap* 변수를 멤버변수로 할당하고 
new LoanBookHeap[8]; 으로 연결된 리스트로 관리하는 방식은 가능할까요?

각 셀렉션트리 및 힙의 내부구조는 링크드리스트로 구현하였습니다!

**Comment by kimsangho611** [comment]
학생분이 하고자하는 방식으로 구현하는 경우 
selection tree를 array 방식으로 구현해야 합니다.

따라서 불가능할 거 같습니다.

-----Original Message-----

**Comment by kang-tw** [comment]
셀렉션트리 또한 링크드 리스트로 구현하였고 8개의 각 힙을 관리하기 위해 배열로 선언하는 것도 안되는걸까요?..

**Comment by kimsangho611** [comment]
그러면 지금 skeleton code상 selection tree node에 heap 자료구조가 들어가도록 되어 있는데,
이렇게 구현하지 않고, selection tree 구현하고, heap 부분을 따로 구현하신건가요?

-----Original Message-----

**Comment by kang-tw** [comment]
아.. 저는 셀렉션 트리의 각 런을 heap으로 생각하고 구현하였습니다...
그래서 각 run의 위의 노드부터 셀렉션트리 노드로 구현한 상황입니다.

Selection  Tree의 각 run은 LoanBookHeap  class로 선언되며, Heap이 정렬되는  경우 
Selection tree로 같이 재정렬된다. LoanBookHeap에 대해서는 다음 절에서 자세히 설명한다.

로 되어있기에..  데이터가 들어오게 되면 힙에 데이터를 삽입 및 정렬하고 정렬 이후 다시 셀렉션 트리를 조정하는 방식으로 구현하였습니다. 이런 방식으로 구현하면 안되는 상황일까요?..

**Comment by kimsangho611** [comment]
지금 학생분이 어떤 식으로 구현이 되어 있는지 명확하게 이해가 잘 가지 않습니다.

아래 그림에서 빨간 네모 부분을 배열로 구현을 했다는 것인지, 아님 아예 완전히 다르게 구현한 것인지 명확히 설명해주시길 바랍니다.
만일 전자라면 상관 없을 거 같지만, 후자라면 잘못된 거 같습니다.

![image](https://github.com/DSLDataStorage/DS_Project_2_2023_2/assets/53908335/f88dd3fb-2cfc-458e-b3b4-7c211006c331)




-----Original Message-----

**Comment by kang-tw** [comment]
혹시 대면으로 질문가능할까요?....

**Comment by kimsangho611** [comment]
새빛관 909호로 오시길 바랍니다

-----Original Message-----
