### ISSUE TITLE
명령어 관련 문의입니다.

### ISSUE THREAD

**Issue by vamosdancar** [DSLDataStorage/DS_Project_2_2023_2#7]
1. LOAD 명령어 수행 시 텍스트 파일(loan_book.txt) 에 데이터가 없으면, LOAD 명령 시 에러 코드를 출력해야 하나요?

2. ADD 명령어 수행 시 도서명이 숫자(1984)인 경우와 띄어쓰기가 있는 도서명(Harry Potter)도 고려를 하여 구현해야 하나요?

**Comment by kimsangho611** [comment]
1. 네 맞습니다.
2. 숫자인 경우까지는 고려하지 않아도 되지만, 띄어쓰기가 있는 경우는 고려하시길 바랍니다. 띄어쓰기를 고려하기 위해 모든 명령어의 인자는 탭으로 구분됩니다.
