### ISSUE TITLE
B+ tree 삽입 관련 -대출 권수가 0인 경우

### ISSUE THREAD

**Issue by JJJangJeongSu** [DSLDataStorage/DS_Project_2_2023_2#8]
안녕하세요 데이터구조설계를 수강중인 2019202025 박정수입니다.

B+ tree 의 load에서 "대출 중인 도서는 B+-tree에 저장한다." 라고 적혀있는데, 
대출 권 수가 0인 경우는 어떻게 되는지 궁금합니다. 

다시 말해, B+-tree는 "대출 가능 도서"를 저장하는지 "대출 중인 도서"를 저장하는지 알고 싶습니다. 감사합니다

**Comment by kimsangho611** [comment]
대출 가능 도서라고 생각하시면 됩니다.
단순하게 loan_book.txt에 저장된 데이터를 모두 저장한다고 생각하시면 됩니다.
