### ISSUE TITLE
도서명 대소문자 구별없이 입력에 대한 질문

### ISSUE THREAD

**Issue by babydragon0073** [DSLDataStorage/DS_Project_2_2023_2#9]
map 자료형을 사용할 시 
데이터를 넣었을 때 대소문자를 구별하여 정렬이 됩니다

map 안의 데이터들을 대소문자 구별없이 정렬할 수 있는 방법이 있나요?

ex) day Data Star 순으로 map에 넣을 때 Data day Star순을 기대했지만 Data Star day로 대소문자를 구별하여 정렬이 됩니다

프로젝트 보고서 그림에 있는 예시 단어들로만 구성하면 딱히 문제없이 순서대로 나오는데 혹시 테스트 케이스 자체에 제한을 두어 
실행하나요?

**Comment by kimsangho611** [comment]
채점을 위한 테스트 케이스의 경우 도서명은 전부 소문자로 테스트할 예정입니다.
